services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data2:
